const getImg = (name) => {
    const path = `/src/assets/images/${name}`; //your imgfile
    const modules = import.meta.globEager("/src/assets/images/*"); 
    return modules[path].default;
}

export const projects = [
    {
        id: 1,
        // date: "Oktoober 4, 2021",
        date: "Oktoober 2021",
        title: "Collatz Conjecture",
        image: getImg("collatz.jpg"),
        lang: "Python",
        github: "https://github.com/freduard/collatz_conjecture",
        figma: "",
        online: "",
        p1: "Tegin selle skripti, et oma oskuseid Pythonis harjutada. Nägin videot selle matemaatilise probleemi kohta, millejärel tuli mõte seda teha. 'Collatz Conjecture' jaoks tuleb võtta mingi number. Kui see on paarisarv, siis tuleb see jagada kahega või korrutada kolmega ja lisada selle 1 kui see ei ole paarisarv. See skript kalkuleerib läbi kõik numbrid lõpmatuseni ja salvestab selle numbri mille peal sai teha kõige rohkem kalkulatsioone, ehk siis jagamist või korrutamist.",
        p2: "Lisasin ka salvestamis feature'i mis laseb sul samast kohast edasi kalkuleerida kui skript kinni panna."
    },
    {
        id: 2,
        // date: "November 5, 2021",
        date: "November 2021",
        title: "Ryan Reynolds E-Portfoolio",
        image: getImg("ryan_reynolds.jpg"),
        lang: "HTML + CSS",
        github: "https://tak19leemet.itmajakas.ee/team3-portfolio/",
        figma: "https://www.figma.com/file/NeiL7NSUinwE0dAxOEQsNG/Desktop",
        online: "https://tak19leemet.itmajakas.ee/team3-portfolio/",
        p1: "Esimese projektina oli vaja 3 päeva jooksul oma meeskonnaga valmis teha E-Portfolio kas reaalse inimese või väljamõeldud tegelase kohta. Projekti lõpptulemus tuli üldjoontes üpris hästi välja. Vahetevahel oli abi vaja CSS'i osas, kuna ma ei saanud siis elementide paigutamisest ja õige koodi struktuuri kirjutamisest nii hästi veel aru, sest olin selle teema õppimisega alles alustanud.",
        p2: "Tagasi vaadates oleksin võinud lehekülje HTML struktuuri juba algselt paremini kodeerida ja organiseerida, kuna lõpuks oli kõik üpris segane ja oli raske koodist aru saada. Arvestades sellega, et see oli mu päris esimene kord kui ma üldse veebilehte arendasin, olen tulemusega rahul."
    },
    {
        id: 3,
        // date: "Detsember 15, 2021",
        date: "Detsember 2021",
        title: "Virtuaalne Instrument",
        image: getImg("arduino_chello.jpg"),
        lang: "JS + HTML + CSS",
        github: "https://github.com/freduard/tiim-5",
        figma: "https://www.figma.com/file/MS84o0iRUgXWLZkr4FUfv8/Tiim5?node-id=0%3A1",
        online: "",
        p1: "Teise projektina pidime tegema virtuaalse muusikainstrumendi, milleks kasutasime Arduinot, veebisaiti ja serverit. Selleks ühendasime Arduino veebisaidiga ja seda serveri abil, kogu töö hõlmas endas ka programmeerimis Javas, JavaScriptis ja Phythonis, mille tulemusena sai virtuaalselt tšellot mängida. Ühendamine toimus serveriga, mis jooksis teise arvuti peal.",
        p2: "Noote sai mängida nii veebisaidi kui ka Arduino peal. Veebisaidil oli ka juba enamjaolt ette tehtud kood, mis visualiseeris hääli JavaScriptiga. Mina tegelesin peamiselt JavaScriptiga ja Githubiga, et need noodid töötaksid. Kahjuks ei tulnud asi välja nii nagu oodatud. Hääl hakkis ja kogu süsteem jooksis väga aeglaselt.",
        p3: "Samuti oli probleeme meeskonnaga, kuna puudus juht, kes kogu tööd oleks suunanud ja koordineerinud. Lisaks mõned meeskonnaliikmed lahkusid poole töö pealt, mis tegi vajaliku tulemuse saavutamise väga raskeks. Kokkuvõttes andis see kõik juurde vajalikku praktilist kogemust meeskonnatöö osas.",
    },
    {
        id: 4,
        // date: "Märts 4, 2022",
        date: "Märts 2022",
        title: "Andmemudeid & planeerimine",
        image: getImg("datamodels_project_planning.webp"),
        lang: "None",
        github: "https://github.com/angsuuu/Project-5---Team-8",
        figma: "",
        online: "",
        p1: "Basically suht timm blah bla blah bla blah bla blah bla blah bla blah bla blah bla blah bla blah bla blah bla blah bla blah bla blah bla blah bla blah bla blah bla blah bla blah bla blah bla blah bla blah bla blah bla blah bla blah bla blah bla blah bla blah bla blah bla blah bla blah bla blah bla",
        p2: "rohkem ei oska öelda",
    },
    {
        id: 5,
        // date: "Märts 25, 2022",
        date: "Märts 2022",
        title: "Andres Kõljalg E-Portfoolio",
        image: getImg("andres_koljalg_portfolio.png"),
        lang: "VueJS + Tailwind",
        github: "https://github.com/andreskoljalg/andres-koljalg-portfolio",
        figma: "",
        online: "https://andres-koljalg-portfolio.pages.dev/",
        p1: "Sain Andresega läbi oma venna tuttavaks, kui ta oli maininud e-portfoolio vajadust. See oli minu esimene päris projekt ja veebiarenduse tööots mida ma sel ajal teinud olin. Selle projekti arendamise käigus sain ma arvan ühe kooli aasta võrra teadmisi juurde veebiarendamises. Alguses mõtlesin, et see on lihtne ja kiire paarinädala töö mis on osutus täiesti vastupidiseks.",
        p2: "Algselt ainukene asi mida ma kasutasin oli TailwindCSS ilma ühegi raamistikuta, mis oli suur viga elementide paigutuse tõttu, kuna elementide klasside read tulid väga massiivsed mistõttu oli ka koodist lõpuks raske aru saada. Peale selle kui ma veel copy-past-isin elemente kuskilt mujalt koodist, siis läheb kõik väga segaseks. On olemas erinevad raamistikud nagu Vue.js mis lahendavad selle probleemi, mida ma muidugi naiivselt ei kasutanud.",
        p3: "Paratamatult pidin ma terve projekti port'ima Vue.js raamistiku peale ja ümber ehitama terve saidi back-end'i süsteemi mis oli pehmelt öeldes piinarikas. Vähemalt nüüd tean, et raamistik on alati vajalik, ükskõik kui suur või väike su projekt tundub.",
    },
    {
        id: 6,
        // date: "Aprill 6, 2022",
        date: "Aprill 2022",
        title: "Muusika poe veebileht",
        image: getImg("music_instrument_store.png"),
        lang: "VueJS + Tailwind",
        github: "https://github.com/TimTimDev/timo-lopuproje",
        figma: "",
        online: "",
        p1: "Basically suht timm blah bla blah bla blah bla blah bla blah bla blah bla blah bla blah bla blah bla blah bla blah bla blah bla blah bla blah bla blah bla blah bla blah bla blah bla blah bla blah bla blah bla blah bla blah bla blah bla blah bla blah bla blah bla blah bla blah bla blah bla blah bla",
        p2: "rohkem ei oska öelda",
    },
    {
        id: 7,
        // date: "Mai 18, 2022",
        date: "Mai 2022",
        title: "Python Image Downscaler",
        image: getImg("python.jpg"),
        lang: "Python",
        github: "https://github.com/freduard/python-image-downscaler",
        figma: "",
        online: "",
        p1: "Tegin selle skripti yhe oma kliendi jaoks kellel oli vaja suures mahus pilte töötelda. See skript skalleerib kõikide piltide resolutsiooni antud protsendi võrra vähemaks ühe folderi sees. Seejärel teeb folderile koopia ja asetab kõik töödeldud pildid sinna sisse.",
        p2: "See osutus palju keerulisemaks kui algselt arvasin, kuna kogu aeg tuli aina rohkem ja rohkem asju juurde millega pidin arvestama. Nagu näiteks mitme operatsioonisüsteemi toetus. Poole peal leidsin ka koodis suure loogika vea misjärel pidin enamus skripti ümber kirjutama palju keerulisema loogikaga."
    },
    {
        id: 8,
        // date: "September 28, 2022",
        date: "September 2022",
        title: "Growtopia Trainer",
        image: getImg("gt.jpg"),
        lang: "C#",
        github: "",
        figma: "",
        online: "",
        p1: "Otsustasin häki või niiöelda 'Trainer'i kallal hakata töötama kui sõpredega tuli suvakas idee seda teha. 'Trainer' tähendab mingisugust programmi millel on suur kollektsioon häkke mingisugusele mängule, nagu näiteks Growtopiale. See ka, nagu tavaliselt, osutus suuremaks ja keerulisemaks projektiks kui ma algselt arvasin. Plaanin lisada veel paljusi feature'eid. Hiljuti sain just valmis MAC aadressi muutja, mis oli suur ettevõtmine kuna pidin õppima kuidas MAC aadressid töötavad, kuidas Windows nendest aru saab ja kasutab ning kuidas MAC aadressi üldse muuta saab.",
        p2: "Hetkel on selle projekti GitHub privaatne, kuid on plaan see kunagi avalikuks teha kui see valmis saab. Kuid sinnani on veel kaua aega, sest selle arendamine on üllatavalt aeganõudev ja mul on veel palju õppida programmide ja häkkide arendamisel.",
    },
]

projects.reverse();